import {
  LucideIcon,
  Fan,
  Axe,
  BellElectric,
  BedDouble,
  House,
  PaintBucket,
  BrickWall,
  Dock,
  LandPlot,
  ToyBrick,
  BrickWallIcon,
  WavesLadder,
  Users,
  BugOff,
  Flame,
  Heater,
  Cctv,
  HomeIcon,
  File,
  Siren,
  Podcast,
  Rabbit,
  Layers,
  Timer,
  Navigation,
  TimerReset,
  Bike,
  Handshake,
  DollarSign,
  BriefcaseBusiness,
  TimerIcon,
  InspectIcon,
  Check,
  Verified,
  Hourglass,
  Headset,
  Bitcoin,
  Receipt,
  FileChartColumnIncreasingIcon,
  BadgeDollarSign,
  Trash,
} from "lucide-react";

export enum AmenityEnum {
  FreeInspection = "FreeInspection",
  OnSiteInspection = "OnSiteInspection",
  WarrantyIncluded = "WarrantyIncluded",
  FlexibleScheduling = "FlexibleScheduling",
  Support247 = "Support247",
  OnlinePayment = "OnlinePayment",
  InvoiceAvailable = "InvoiceAvailable",
  FinancingOptions = "FinancingOptions",
  ReferralDiscount = "ReferralDiscount",
  PostJobCleanup = "PostJobCleanup",
}

export const AmenityIcons: Record<AmenityEnum, LucideIcon> = {
  FreeInspection: InspectIcon,
  OnSiteInspection: Check,
  WarrantyIncluded: Verified,
  FlexibleScheduling: Hourglass,
  Support247: Headset,
  OnlinePayment: Bitcoin,
  InvoiceAvailable: Receipt,
  FinancingOptions: FileChartColumnIncreasingIcon,
  ReferralDiscount: BadgeDollarSign,
  PostJobCleanup: Trash,
};

export enum HighlightEnum {
  LicensedProfessional = "LicensedProfessional",
  EmergencySupport = "EmergencySupport",
  FreeConsultation = "FreeConsultation",
  QuickResponse = "QuickResponse",
  QualityGuarantee = "QualityGuarantee",
  FlexibleHours = "FlexibleHours",
  RemoteSupportAvailable = "RemoteSupportAvailable",
  FreeEstimates = "FreeEstimates",
  SameDayService = "SameDayService",
  EcoFriendly = "EcoFriendly",
  AffordablePricing = "AffordablePricing",
  LocallyOwned = "LocallyOwned",
  YearsOfExperience = "YearsOfExperience",
}

export const HighlightIcons: Record<HighlightEnum, LucideIcon> = {
  LicensedProfessional: File,
  EmergencySupport: Siren,
  FreeConsultation: Podcast,
  QuickResponse: Rabbit,
  QualityGuarantee: Layers,
  FlexibleHours: Timer,
  RemoteSupportAvailable: Navigation,
  FreeEstimates: TimerReset,
  SameDayService: Bike,
  EcoFriendly: Handshake,
  AffordablePricing: DollarSign,
  LocallyOwned: BriefcaseBusiness,
  YearsOfExperience: TimerIcon,
};

export enum ContractorTypeEnum {
  HVAC = "HVAC",
  Plumbing = "Plumbing",
  Electrical = "Electrical",
  Carpentry = "Carpentry",
  Roofing = "Roofing",
  Painting = "Painting",
  Drywall = "Drywall",
  ApplianceRepair = "ApplianceRepair",
  LandScaping = "LandScaping",
  Interlocking = "Interlocking",
  Masonry = "Masonry",
  Flooring = "Flooring",
  Handyman = "Handyman",
  PestControl = "PestControl",
  Welding = "Welding",
  Insulation = "Insulation",
  SecuritySystems = "SecuritySystems",
  SmartHome = "SmartHome",
}

export const ContractorTypeIcons: Record<ContractorTypeEnum, LucideIcon> = {
  HVAC: Fan,
  Plumbing: Axe,
  Electrical: BellElectric,
  Carpentry: BedDouble,
  Roofing: House,
  Painting: PaintBucket,
  Drywall: BrickWall,
  ApplianceRepair: Dock,
  LandScaping: LandPlot,
  Interlocking: ToyBrick,
  Masonry: BrickWallIcon,
  Flooring: WavesLadder,
  Handyman: Users,
  PestControl: BugOff,
  Welding: Flame,
  Insulation: Heater,
  SecuritySystems: Cctv,
  SmartHome: HomeIcon,
};

// Add this constant at the end of the file
export const NAVBAR_HEIGHT = 48; // in pixels

// Test users for development
export const testUsers = {
  customer: {
    username: "Carol White",
    userId: "us-east-2:76543210-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "carol.white@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  customerRole: "customer",
  manager: {
    username: "John Smith",
    userId: "us-east-2:12345678-90ab-cdef-1234-567890abcdef",
    signInDetails: {
      loginId: "john.smith@example.com",
      authFlowType: "USER_SRP_AUTH",
    },
  },
  managerRole: "manager",
};
